### PR TITLE
tokio 0.2 support

### PR DESCRIPTION
**Pull request by ivomurrell**
This PR adds async/await support to the library by upgrading to the new versions of `tokio` and `dbus-tokio`, using the new semantics and idioms they've introduced.

The differences to the API for the end user of this library don't end up being that large. However, the libraries used to power `connman-rs` have changed quite significantly (`futures 0.1` combinators mostly being eschewed for async/await syntax, `dbus-tokio 0.5` has been simplified) and this is reflected in the updated examples.

For the purposes of CI testing I'm pulling in the master branch of the `dbus-rs` libraries which includes a fix to asynchronous method calls timing out when the reply contains a large payload, something very common with the Connman interfaces. We won't want to merge this PR until the fix has been pushed to crates.io.

Feel free to pick and choose what features you want to bring into your own `tokio 0.2` branch!

### CODE REVIEW

**Comment by ivomurrell** [comment]
Wanted to split forcing explicit timeouts into a separate PR to discuss, but the Travis failures have made it clear to me that it's necessary to always have them configurable. Not sure why the update to `dbus-tokio`/`tokio 0.2` is causing these timeout problems though.

**Comment by jmagnuson** [comment]
I'm wondering if the travis failures (at least the last one) aren't just an artifact of VM persistence across builds. In any case, I restarted the latest build after some time and it passed. Eventually, I plan to containerize the simulation environment to mitigate this sort of thing.

**Comment by jmagnuson** [comment]
Hey @ivoisbelongtous, were you just wanting me to cherry-pick these changes, or still working on a non-draft PR? Fine either way, just looking for clarification.

**Comment by ivomurrell** [comment]
It's up to you of course, but I was imagining it would mostly be useful as a working baseline for you to cherry-pick from whilst working on your implementation. Feel free to close if you want!

**Comment by jmagnuson** [comment]
Uff-da, I let this sit for too long. Merging as-is-- I also have a branch forthcoming which updates to tokio 1.

**Pull request merged**
